# Generated by Django 5.2.5 on 2025-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='signature_consent',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('other', 'Other ID')], default=1, help_text='Type of identification document', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='other_id_name',
            field=models.CharField(blank=True, help_text="Name of other ID type (if 'other' is selected)", max_length=100),
        ),
    ]
