# Generated by Django 5.2.5 on 2025-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0002_remove_reservation_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_passport_photo',
            field=models.ImageField(blank=True, help_text='ID or Passport photo', null=True, upload_to='customers/id_photos/'),
        ),
    ]
