# Generated by Django 5.2.5 on 2025-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0003_alter_customer_id_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(default=1, help_text='Unique 6-character booking identifier', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
