# Generated by Django 5.2.5 on 2025-09-25 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0004_reservation_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Name of the room (e.g., Room 1, Mountain View, etc.)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this room is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(help_text='Room type this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='kilimanager.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_type', 'room_name'],
                'unique_together': {('room_type', 'room_name')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Assigned specific room (set when reservation is confirmed)', null=True, on_delete=django.db.models.deletion.CASCADE, to='kilimanager.room'),
        ),
    ]
