# Generated by Django 5.2.5 on 2025-09-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0005_room_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting_checkin', 'Waiting Check-in'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='pending', help_text='Reservation status', max_length=20),
        ),
    ]
