# Generated by Django 5.2.5 on 2025-09-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimanager', '0006_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('partial', 'Partial Payment')], default='not_paid', help_text='Payment status', max_length=20),
        ),
    ]
